# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67d86c6504769b39bf815fcbde22baa5ac5e585b57946283a0761e02283f70f2b31451ec052184545023ee9f3ac8cb70cbda5df0444cdfed91c7daf738c10a29

test:
  secret_key_base: 97a62b057c165058b9b18f4724d6b621f8f488a8accf3257c3f2b3ead24b24f564e9db99ce46f2c82400d89316229adb20ab19b707f828ce43566e8406024454

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
